// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/Perajit/expense-tracker-go/internal/auth"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Login(dto auth.LoginRequest, userProvider auth.UserProvider) (*auth.TokenResponse, error) {
	ret := _mock.Called(dto, userProvider)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *auth.TokenResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(auth.LoginRequest, auth.UserProvider) (*auth.TokenResponse, error)); ok {
		return returnFunc(dto, userProvider)
	}
	if returnFunc, ok := ret.Get(0).(func(auth.LoginRequest, auth.UserProvider) *auth.TokenResponse); ok {
		r0 = returnFunc(dto, userProvider)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.TokenResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(auth.LoginRequest, auth.UserProvider) error); ok {
		r1 = returnFunc(dto, userProvider)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - dto auth.LoginRequest
//   - userProvider auth.UserProvider
func (_e *MockAuthService_Expecter) Login(dto interface{}, userProvider interface{}) *MockAuthService_Login_Call {
	return &MockAuthService_Login_Call{Call: _e.mock.On("Login", dto, userProvider)}
}

func (_c *MockAuthService_Login_Call) Run(run func(dto auth.LoginRequest, userProvider auth.UserProvider)) *MockAuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 auth.LoginRequest
		if args[0] != nil {
			arg0 = args[0].(auth.LoginRequest)
		}
		var arg1 auth.UserProvider
		if args[1] != nil {
			arg1 = args[1].(auth.UserProvider)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_Login_Call) Return(tokenResponse *auth.TokenResponse, err error) *MockAuthService_Login_Call {
	_c.Call.Return(tokenResponse, err)
	return _c
}

func (_c *MockAuthService_Login_Call) RunAndReturn(run func(dto auth.LoginRequest, userProvider auth.UserProvider) (*auth.TokenResponse, error)) *MockAuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Refresh(refresh string) (*auth.TokenResponse, error) {
	ret := _mock.Called(refresh)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 *auth.TokenResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*auth.TokenResponse, error)); ok {
		return returnFunc(refresh)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *auth.TokenResponse); ok {
		r0 = returnFunc(refresh)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.TokenResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(refresh)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type MockAuthService_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - refresh string
func (_e *MockAuthService_Expecter) Refresh(refresh interface{}) *MockAuthService_Refresh_Call {
	return &MockAuthService_Refresh_Call{Call: _e.mock.On("Refresh", refresh)}
}

func (_c *MockAuthService_Refresh_Call) Run(run func(refresh string)) *MockAuthService_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthService_Refresh_Call) Return(tokenResponse *auth.TokenResponse, err error) *MockAuthService_Refresh_Call {
	_c.Call.Return(tokenResponse, err)
	return _c
}

func (_c *MockAuthService_Refresh_Call) RunAndReturn(run func(refresh string) (*auth.TokenResponse, error)) *MockAuthService_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Verify(access string) (uint, error) {
	ret := _mock.Called(access)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 uint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (uint, error)); ok {
		return returnFunc(access)
	}
	if returnFunc, ok := ret.Get(0).(func(string) uint); ok {
		r0 = returnFunc(access)
	} else {
		r0 = ret.Get(0).(uint)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(access)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockAuthService_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - access string
func (_e *MockAuthService_Expecter) Verify(access interface{}) *MockAuthService_Verify_Call {
	return &MockAuthService_Verify_Call{Call: _e.mock.On("Verify", access)}
}

func (_c *MockAuthService_Verify_Call) Run(run func(access string)) *MockAuthService_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthService_Verify_Call) Return(v uint, err error) *MockAuthService_Verify_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockAuthService_Verify_Call) RunAndReturn(run func(access string) (uint, error)) *MockAuthService_Verify_Call {
	_c.Call.Return(run)
	return _c
}
