// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/Perajit/expense-tracker-go/internal/auth"
	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockTokenRepository creates a new instance of MockTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenRepository {
	mock := &MockTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenRepository is an autogenerated mock type for the TokenRepository type
type MockTokenRepository struct {
	mock.Mock
}

type MockTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenRepository) EXPECT() *MockTokenRepository_Expecter {
	return &MockTokenRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTokenRepository
func (_mock *MockTokenRepository) Create(token *auth.TokenEntity) error {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*auth.TokenEntity) error); ok {
		r0 = returnFunc(token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTokenRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - token *auth.TokenEntity
func (_e *MockTokenRepository_Expecter) Create(token interface{}) *MockTokenRepository_Create_Call {
	return &MockTokenRepository_Create_Call{Call: _e.mock.On("Create", token)}
}

func (_c *MockTokenRepository_Create_Call) Run(run func(token *auth.TokenEntity)) *MockTokenRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *auth.TokenEntity
		if args[0] != nil {
			arg0 = args[0].(*auth.TokenEntity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenRepository_Create_Call) Return(err error) *MockTokenRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenRepository_Create_Call) RunAndReturn(run func(token *auth.TokenEntity) error) *MockTokenRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTokenID provides a mock function for the type MockTokenRepository
func (_mock *MockTokenRepository) GetByTokenID(jti string) (*auth.TokenEntity, error) {
	ret := _mock.Called(jti)

	if len(ret) == 0 {
		panic("no return value specified for GetByTokenID")
	}

	var r0 *auth.TokenEntity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*auth.TokenEntity, error)); ok {
		return returnFunc(jti)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *auth.TokenEntity); ok {
		r0 = returnFunc(jti)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.TokenEntity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(jti)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenRepository_GetByTokenID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTokenID'
type MockTokenRepository_GetByTokenID_Call struct {
	*mock.Call
}

// GetByTokenID is a helper method to define mock.On call
//   - jti string
func (_e *MockTokenRepository_Expecter) GetByTokenID(jti interface{}) *MockTokenRepository_GetByTokenID_Call {
	return &MockTokenRepository_GetByTokenID_Call{Call: _e.mock.On("GetByTokenID", jti)}
}

func (_c *MockTokenRepository_GetByTokenID_Call) Run(run func(jti string)) *MockTokenRepository_GetByTokenID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenRepository_GetByTokenID_Call) Return(tokenEntity *auth.TokenEntity, err error) *MockTokenRepository_GetByTokenID_Call {
	_c.Call.Return(tokenEntity, err)
	return _c
}

func (_c *MockTokenRepository_GetByTokenID_Call) RunAndReturn(run func(jti string) (*auth.TokenEntity, error)) *MockTokenRepository_GetByTokenID_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function for the type MockTokenRepository
func (_mock *MockTokenRepository) Revoke(token *auth.TokenEntity) error {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*auth.TokenEntity) error); ok {
		r0 = returnFunc(token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenRepository_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockTokenRepository_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - token *auth.TokenEntity
func (_e *MockTokenRepository_Expecter) Revoke(token interface{}) *MockTokenRepository_Revoke_Call {
	return &MockTokenRepository_Revoke_Call{Call: _e.mock.On("Revoke", token)}
}

func (_c *MockTokenRepository_Revoke_Call) Run(run func(token *auth.TokenEntity)) *MockTokenRepository_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *auth.TokenEntity
		if args[0] != nil {
			arg0 = args[0].(*auth.TokenEntity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenRepository_Revoke_Call) Return(err error) *MockTokenRepository_Revoke_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenRepository_Revoke_Call) RunAndReturn(run func(token *auth.TokenEntity) error) *MockTokenRepository_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllFromUser provides a mock function for the type MockTokenRepository
func (_mock *MockTokenRepository) RevokeAllFromUser(userID uint) error {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllFromUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint) error); ok {
		r0 = returnFunc(userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenRepository_RevokeAllFromUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllFromUser'
type MockTokenRepository_RevokeAllFromUser_Call struct {
	*mock.Call
}

// RevokeAllFromUser is a helper method to define mock.On call
//   - userID uint
func (_e *MockTokenRepository_Expecter) RevokeAllFromUser(userID interface{}) *MockTokenRepository_RevokeAllFromUser_Call {
	return &MockTokenRepository_RevokeAllFromUser_Call{Call: _e.mock.On("RevokeAllFromUser", userID)}
}

func (_c *MockTokenRepository_RevokeAllFromUser_Call) Run(run func(userID uint)) *MockTokenRepository_RevokeAllFromUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenRepository_RevokeAllFromUser_Call) Return(err error) *MockTokenRepository_RevokeAllFromUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenRepository_RevokeAllFromUser_Call) RunAndReturn(run func(userID uint) error) *MockTokenRepository_RevokeAllFromUser_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeByTokenID provides a mock function for the type MockTokenRepository
func (_mock *MockTokenRepository) RevokeByTokenID(jti string) error {
	ret := _mock.Called(jti)

	if len(ret) == 0 {
		panic("no return value specified for RevokeByTokenID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(jti)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenRepository_RevokeByTokenID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeByTokenID'
type MockTokenRepository_RevokeByTokenID_Call struct {
	*mock.Call
}

// RevokeByTokenID is a helper method to define mock.On call
//   - jti string
func (_e *MockTokenRepository_Expecter) RevokeByTokenID(jti interface{}) *MockTokenRepository_RevokeByTokenID_Call {
	return &MockTokenRepository_RevokeByTokenID_Call{Call: _e.mock.On("RevokeByTokenID", jti)}
}

func (_c *MockTokenRepository_RevokeByTokenID_Call) Run(run func(jti string)) *MockTokenRepository_RevokeByTokenID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenRepository_RevokeByTokenID_Call) Return(err error) *MockTokenRepository_RevokeByTokenID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenRepository_RevokeByTokenID_Call) RunAndReturn(run func(jti string) error) *MockTokenRepository_RevokeByTokenID_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function for the type MockTokenRepository
func (_mock *MockTokenRepository) WithTx(tx *gorm.DB) auth.TokenRepository {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 auth.TokenRepository
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) auth.TokenRepository); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(auth.TokenRepository)
		}
	}
	return r0
}

// MockTokenRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockTokenRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *MockTokenRepository_Expecter) WithTx(tx interface{}) *MockTokenRepository_WithTx_Call {
	return &MockTokenRepository_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *MockTokenRepository_WithTx_Call) Run(run func(tx *gorm.DB)) *MockTokenRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenRepository_WithTx_Call) Return(tokenRepository auth.TokenRepository) *MockTokenRepository_WithTx_Call {
	_c.Call.Return(tokenRepository)
	return _c
}

func (_c *MockTokenRepository_WithTx_Call) RunAndReturn(run func(tx *gorm.DB) auth.TokenRepository) *MockTokenRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}
