// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/Perajit/expense-tracker-go/internal/user"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockUserService
func (_mock *MockUserService) CreateUser(dto user.CreateUserRequest) (*user.UserEntity, error) {
	ret := _mock.Called(dto)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *user.UserEntity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(user.CreateUserRequest) (*user.UserEntity, error)); ok {
		return returnFunc(dto)
	}
	if returnFunc, ok := ret.Get(0).(func(user.CreateUserRequest) *user.UserEntity); ok {
		r0 = returnFunc(dto)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.UserEntity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(user.CreateUserRequest) error); ok {
		r1 = returnFunc(dto)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserService_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - dto user.CreateUserRequest
func (_e *MockUserService_Expecter) CreateUser(dto interface{}) *MockUserService_CreateUser_Call {
	return &MockUserService_CreateUser_Call{Call: _e.mock.On("CreateUser", dto)}
}

func (_c *MockUserService_CreateUser_Call) Run(run func(dto user.CreateUserRequest)) *MockUserService_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 user.CreateUserRequest
		if args[0] != nil {
			arg0 = args[0].(user.CreateUserRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserService_CreateUser_Call) Return(userEntity *user.UserEntity, err error) *MockUserService_CreateUser_Call {
	_c.Call.Return(userEntity, err)
	return _c
}

func (_c *MockUserService_CreateUser_Call) RunAndReturn(run func(dto user.CreateUserRequest) (*user.UserEntity, error)) *MockUserService_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type MockUserService
func (_mock *MockUserService) DeleteUser(id uint, authUserID uint) error {
	ret := _mock.Called(id, authUserID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint, uint) error); ok {
		r0 = returnFunc(id, authUserID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserService_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockUserService_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - id uint
//   - authUserID uint
func (_e *MockUserService_Expecter) DeleteUser(id interface{}, authUserID interface{}) *MockUserService_DeleteUser_Call {
	return &MockUserService_DeleteUser_Call{Call: _e.mock.On("DeleteUser", id, authUserID)}
}

func (_c *MockUserService_DeleteUser_Call) Run(run func(id uint, authUserID uint)) *MockUserService_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_DeleteUser_Call) Return(err error) *MockUserService_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserService_DeleteUser_Call) RunAndReturn(run func(id uint, authUserID uint) error) *MockUserService_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockUserService
func (_mock *MockUserService) GetUserByID(id uint, authUserID uint) (*user.UserEntity, error) {
	ret := _mock.Called(id, authUserID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *user.UserEntity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint, uint) (*user.UserEntity, error)); ok {
		return returnFunc(id, authUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, uint) *user.UserEntity); ok {
		r0 = returnFunc(id, authUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.UserEntity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint, uint) error); ok {
		r1 = returnFunc(id, authUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUserService_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - id uint
//   - authUserID uint
func (_e *MockUserService_Expecter) GetUserByID(id interface{}, authUserID interface{}) *MockUserService_GetUserByID_Call {
	return &MockUserService_GetUserByID_Call{Call: _e.mock.On("GetUserByID", id, authUserID)}
}

func (_c *MockUserService_GetUserByID_Call) Run(run func(id uint, authUserID uint)) *MockUserService_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_GetUserByID_Call) Return(userEntity *user.UserEntity, err error) *MockUserService_GetUserByID_Call {
	_c.Call.Return(userEntity, err)
	return _c
}

func (_c *MockUserService_GetUserByID_Call) RunAndReturn(run func(id uint, authUserID uint) (*user.UserEntity, error)) *MockUserService_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByUsername provides a mock function for the type MockUserService
func (_mock *MockUserService) GetUserByUsername(email string) (*user.UserEntity, error) {
	ret := _mock.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUsername")
	}

	var r0 *user.UserEntity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*user.UserEntity, error)); ok {
		return returnFunc(email)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *user.UserEntity); ok {
		r0 = returnFunc(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.UserEntity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_GetUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByUsername'
type MockUserService_GetUserByUsername_Call struct {
	*mock.Call
}

// GetUserByUsername is a helper method to define mock.On call
//   - email string
func (_e *MockUserService_Expecter) GetUserByUsername(email interface{}) *MockUserService_GetUserByUsername_Call {
	return &MockUserService_GetUserByUsername_Call{Call: _e.mock.On("GetUserByUsername", email)}
}

func (_c *MockUserService_GetUserByUsername_Call) Run(run func(email string)) *MockUserService_GetUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserService_GetUserByUsername_Call) Return(userEntity *user.UserEntity, err error) *MockUserService_GetUserByUsername_Call {
	_c.Call.Return(userEntity, err)
	return _c
}

func (_c *MockUserService_GetUserByUsername_Call) RunAndReturn(run func(email string) (*user.UserEntity, error)) *MockUserService_GetUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type MockUserService
func (_mock *MockUserService) UpdateUser(id uint, authUserID uint, dto user.UpdateUserRequest) error {
	ret := _mock.Called(id, authUserID, dto)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint, uint, user.UpdateUserRequest) error); ok {
		r0 = returnFunc(id, authUserID, dto)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserService_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockUserService_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - id uint
//   - authUserID uint
//   - dto user.UpdateUserRequest
func (_e *MockUserService_Expecter) UpdateUser(id interface{}, authUserID interface{}, dto interface{}) *MockUserService_UpdateUser_Call {
	return &MockUserService_UpdateUser_Call{Call: _e.mock.On("UpdateUser", id, authUserID, dto)}
}

func (_c *MockUserService_UpdateUser_Call) Run(run func(id uint, authUserID uint, dto user.UpdateUserRequest)) *MockUserService_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 user.UpdateUserRequest
		if args[2] != nil {
			arg2 = args[2].(user.UpdateUserRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserService_UpdateUser_Call) Return(err error) *MockUserService_UpdateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserService_UpdateUser_Call) RunAndReturn(run func(id uint, authUserID uint, dto user.UpdateUserRequest) error) *MockUserService_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}
