// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/Perajit/expense-tracker-go/internal/expense"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTagService creates a new instance of MockTagService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTagService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTagService {
	mock := &MockTagService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTagService is an autogenerated mock type for the TagService type
type MockTagService struct {
	mock.Mock
}

type MockTagService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTagService) EXPECT() *MockTagService_Expecter {
	return &MockTagService_Expecter{mock: &_m.Mock}
}

// CreateTag provides a mock function for the type MockTagService
func (_mock *MockTagService) CreateTag(authUserID uint, dto expense.CreateTagRequest) (*expense.TagEntity, error) {
	ret := _mock.Called(authUserID, dto)

	if len(ret) == 0 {
		panic("no return value specified for CreateTag")
	}

	var r0 *expense.TagEntity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint, expense.CreateTagRequest) (*expense.TagEntity, error)); ok {
		return returnFunc(authUserID, dto)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, expense.CreateTagRequest) *expense.TagEntity); ok {
		r0 = returnFunc(authUserID, dto)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*expense.TagEntity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint, expense.CreateTagRequest) error); ok {
		r1 = returnFunc(authUserID, dto)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagService_CreateTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTag'
type MockTagService_CreateTag_Call struct {
	*mock.Call
}

// CreateTag is a helper method to define mock.On call
//   - authUserID uint
//   - dto expense.CreateTagRequest
func (_e *MockTagService_Expecter) CreateTag(authUserID interface{}, dto interface{}) *MockTagService_CreateTag_Call {
	return &MockTagService_CreateTag_Call{Call: _e.mock.On("CreateTag", authUserID, dto)}
}

func (_c *MockTagService_CreateTag_Call) Run(run func(authUserID uint, dto expense.CreateTagRequest)) *MockTagService_CreateTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 expense.CreateTagRequest
		if args[1] != nil {
			arg1 = args[1].(expense.CreateTagRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTagService_CreateTag_Call) Return(tagEntity *expense.TagEntity, err error) *MockTagService_CreateTag_Call {
	_c.Call.Return(tagEntity, err)
	return _c
}

func (_c *MockTagService_CreateTag_Call) RunAndReturn(run func(authUserID uint, dto expense.CreateTagRequest) (*expense.TagEntity, error)) *MockTagService_CreateTag_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTag provides a mock function for the type MockTagService
func (_mock *MockTagService) DeleteTag(id uint, authUserID uint) error {
	ret := _mock.Called(id, authUserID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTag")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint, uint) error); ok {
		r0 = returnFunc(id, authUserID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTagService_DeleteTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTag'
type MockTagService_DeleteTag_Call struct {
	*mock.Call
}

// DeleteTag is a helper method to define mock.On call
//   - id uint
//   - authUserID uint
func (_e *MockTagService_Expecter) DeleteTag(id interface{}, authUserID interface{}) *MockTagService_DeleteTag_Call {
	return &MockTagService_DeleteTag_Call{Call: _e.mock.On("DeleteTag", id, authUserID)}
}

func (_c *MockTagService_DeleteTag_Call) Run(run func(id uint, authUserID uint)) *MockTagService_DeleteTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTagService_DeleteTag_Call) Return(err error) *MockTagService_DeleteTag_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTagService_DeleteTag_Call) RunAndReturn(run func(id uint, authUserID uint) error) *MockTagService_DeleteTag_Call {
	_c.Call.Return(run)
	return _c
}

// GetTagByID provides a mock function for the type MockTagService
func (_mock *MockTagService) GetTagByID(id uint, authUserID uint) (*expense.TagEntity, error) {
	ret := _mock.Called(id, authUserID)

	if len(ret) == 0 {
		panic("no return value specified for GetTagByID")
	}

	var r0 *expense.TagEntity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint, uint) (*expense.TagEntity, error)); ok {
		return returnFunc(id, authUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, uint) *expense.TagEntity); ok {
		r0 = returnFunc(id, authUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*expense.TagEntity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint, uint) error); ok {
		r1 = returnFunc(id, authUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagService_GetTagByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTagByID'
type MockTagService_GetTagByID_Call struct {
	*mock.Call
}

// GetTagByID is a helper method to define mock.On call
//   - id uint
//   - authUserID uint
func (_e *MockTagService_Expecter) GetTagByID(id interface{}, authUserID interface{}) *MockTagService_GetTagByID_Call {
	return &MockTagService_GetTagByID_Call{Call: _e.mock.On("GetTagByID", id, authUserID)}
}

func (_c *MockTagService_GetTagByID_Call) Run(run func(id uint, authUserID uint)) *MockTagService_GetTagByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTagService_GetTagByID_Call) Return(tagEntity *expense.TagEntity, err error) *MockTagService_GetTagByID_Call {
	_c.Call.Return(tagEntity, err)
	return _c
}

func (_c *MockTagService_GetTagByID_Call) RunAndReturn(run func(id uint, authUserID uint) (*expense.TagEntity, error)) *MockTagService_GetTagByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTags provides a mock function for the type MockTagService
func (_mock *MockTagService) GetTags(authUserID uint) ([]expense.TagEntity, error) {
	ret := _mock.Called(authUserID)

	if len(ret) == 0 {
		panic("no return value specified for GetTags")
	}

	var r0 []expense.TagEntity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) ([]expense.TagEntity, error)); ok {
		return returnFunc(authUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) []expense.TagEntity); ok {
		r0 = returnFunc(authUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]expense.TagEntity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(authUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagService_GetTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTags'
type MockTagService_GetTags_Call struct {
	*mock.Call
}

// GetTags is a helper method to define mock.On call
//   - authUserID uint
func (_e *MockTagService_Expecter) GetTags(authUserID interface{}) *MockTagService_GetTags_Call {
	return &MockTagService_GetTags_Call{Call: _e.mock.On("GetTags", authUserID)}
}

func (_c *MockTagService_GetTags_Call) Run(run func(authUserID uint)) *MockTagService_GetTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTagService_GetTags_Call) Return(tagEntitys []expense.TagEntity, err error) *MockTagService_GetTags_Call {
	_c.Call.Return(tagEntitys, err)
	return _c
}

func (_c *MockTagService_GetTags_Call) RunAndReturn(run func(authUserID uint) ([]expense.TagEntity, error)) *MockTagService_GetTags_Call {
	_c.Call.Return(run)
	return _c
}

// GetTagsByIDs provides a mock function for the type MockTagService
func (_mock *MockTagService) GetTagsByIDs(ids []uint, authUserID uint) ([]expense.TagEntity, error) {
	ret := _mock.Called(ids, authUserID)

	if len(ret) == 0 {
		panic("no return value specified for GetTagsByIDs")
	}

	var r0 []expense.TagEntity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]uint, uint) ([]expense.TagEntity, error)); ok {
		return returnFunc(ids, authUserID)
	}
	if returnFunc, ok := ret.Get(0).(func([]uint, uint) []expense.TagEntity); ok {
		r0 = returnFunc(ids, authUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]expense.TagEntity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]uint, uint) error); ok {
		r1 = returnFunc(ids, authUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagService_GetTagsByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTagsByIDs'
type MockTagService_GetTagsByIDs_Call struct {
	*mock.Call
}

// GetTagsByIDs is a helper method to define mock.On call
//   - ids []uint
//   - authUserID uint
func (_e *MockTagService_Expecter) GetTagsByIDs(ids interface{}, authUserID interface{}) *MockTagService_GetTagsByIDs_Call {
	return &MockTagService_GetTagsByIDs_Call{Call: _e.mock.On("GetTagsByIDs", ids, authUserID)}
}

func (_c *MockTagService_GetTagsByIDs_Call) Run(run func(ids []uint, authUserID uint)) *MockTagService_GetTagsByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []uint
		if args[0] != nil {
			arg0 = args[0].([]uint)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTagService_GetTagsByIDs_Call) Return(tagEntitys []expense.TagEntity, err error) *MockTagService_GetTagsByIDs_Call {
	_c.Call.Return(tagEntitys, err)
	return _c
}

func (_c *MockTagService_GetTagsByIDs_Call) RunAndReturn(run func(ids []uint, authUserID uint) ([]expense.TagEntity, error)) *MockTagService_GetTagsByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTag provides a mock function for the type MockTagService
func (_mock *MockTagService) UpdateTag(id uint, authUserID uint, dto expense.UpdateTagRequest) error {
	ret := _mock.Called(id, authUserID, dto)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTag")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint, uint, expense.UpdateTagRequest) error); ok {
		r0 = returnFunc(id, authUserID, dto)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTagService_UpdateTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTag'
type MockTagService_UpdateTag_Call struct {
	*mock.Call
}

// UpdateTag is a helper method to define mock.On call
//   - id uint
//   - authUserID uint
//   - dto expense.UpdateTagRequest
func (_e *MockTagService_Expecter) UpdateTag(id interface{}, authUserID interface{}, dto interface{}) *MockTagService_UpdateTag_Call {
	return &MockTagService_UpdateTag_Call{Call: _e.mock.On("UpdateTag", id, authUserID, dto)}
}

func (_c *MockTagService_UpdateTag_Call) Run(run func(id uint, authUserID uint, dto expense.UpdateTagRequest)) *MockTagService_UpdateTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 expense.UpdateTagRequest
		if args[2] != nil {
			arg2 = args[2].(expense.UpdateTagRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTagService_UpdateTag_Call) Return(err error) *MockTagService_UpdateTag_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTagService_UpdateTag_Call) RunAndReturn(run func(id uint, authUserID uint, dto expense.UpdateTagRequest) error) *MockTagService_UpdateTag_Call {
	_c.Call.Return(run)
	return _c
}
