// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/Perajit/expense-tracker-go/internal/expense"
	mock "github.com/stretchr/testify/mock"
)

// NewMockExpenseService creates a new instance of MockExpenseService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExpenseService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExpenseService {
	mock := &MockExpenseService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExpenseService is an autogenerated mock type for the ExpenseService type
type MockExpenseService struct {
	mock.Mock
}

type MockExpenseService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExpenseService) EXPECT() *MockExpenseService_Expecter {
	return &MockExpenseService_Expecter{mock: &_m.Mock}
}

// CreateExpense provides a mock function for the type MockExpenseService
func (_mock *MockExpenseService) CreateExpense(authUserID uint, dto expense.CreateExpenseRequest) (*expense.ExpenseEntity, error) {
	ret := _mock.Called(authUserID, dto)

	if len(ret) == 0 {
		panic("no return value specified for CreateExpense")
	}

	var r0 *expense.ExpenseEntity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint, expense.CreateExpenseRequest) (*expense.ExpenseEntity, error)); ok {
		return returnFunc(authUserID, dto)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, expense.CreateExpenseRequest) *expense.ExpenseEntity); ok {
		r0 = returnFunc(authUserID, dto)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*expense.ExpenseEntity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint, expense.CreateExpenseRequest) error); ok {
		r1 = returnFunc(authUserID, dto)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExpenseService_CreateExpense_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateExpense'
type MockExpenseService_CreateExpense_Call struct {
	*mock.Call
}

// CreateExpense is a helper method to define mock.On call
//   - authUserID uint
//   - dto expense.CreateExpenseRequest
func (_e *MockExpenseService_Expecter) CreateExpense(authUserID interface{}, dto interface{}) *MockExpenseService_CreateExpense_Call {
	return &MockExpenseService_CreateExpense_Call{Call: _e.mock.On("CreateExpense", authUserID, dto)}
}

func (_c *MockExpenseService_CreateExpense_Call) Run(run func(authUserID uint, dto expense.CreateExpenseRequest)) *MockExpenseService_CreateExpense_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 expense.CreateExpenseRequest
		if args[1] != nil {
			arg1 = args[1].(expense.CreateExpenseRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockExpenseService_CreateExpense_Call) Return(expenseEntity *expense.ExpenseEntity, err error) *MockExpenseService_CreateExpense_Call {
	_c.Call.Return(expenseEntity, err)
	return _c
}

func (_c *MockExpenseService_CreateExpense_Call) RunAndReturn(run func(authUserID uint, dto expense.CreateExpenseRequest) (*expense.ExpenseEntity, error)) *MockExpenseService_CreateExpense_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExpense provides a mock function for the type MockExpenseService
func (_mock *MockExpenseService) DeleteExpense(id uint, authUserID uint) error {
	ret := _mock.Called(id, authUserID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpense")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint, uint) error); ok {
		r0 = returnFunc(id, authUserID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExpenseService_DeleteExpense_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpense'
type MockExpenseService_DeleteExpense_Call struct {
	*mock.Call
}

// DeleteExpense is a helper method to define mock.On call
//   - id uint
//   - authUserID uint
func (_e *MockExpenseService_Expecter) DeleteExpense(id interface{}, authUserID interface{}) *MockExpenseService_DeleteExpense_Call {
	return &MockExpenseService_DeleteExpense_Call{Call: _e.mock.On("DeleteExpense", id, authUserID)}
}

func (_c *MockExpenseService_DeleteExpense_Call) Run(run func(id uint, authUserID uint)) *MockExpenseService_DeleteExpense_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockExpenseService_DeleteExpense_Call) Return(err error) *MockExpenseService_DeleteExpense_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExpenseService_DeleteExpense_Call) RunAndReturn(run func(id uint, authUserID uint) error) *MockExpenseService_DeleteExpense_Call {
	_c.Call.Return(run)
	return _c
}

// GetExpenseByID provides a mock function for the type MockExpenseService
func (_mock *MockExpenseService) GetExpenseByID(id uint, authUserID uint) (*expense.ExpenseEntity, error) {
	ret := _mock.Called(id, authUserID)

	if len(ret) == 0 {
		panic("no return value specified for GetExpenseByID")
	}

	var r0 *expense.ExpenseEntity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint, uint) (*expense.ExpenseEntity, error)); ok {
		return returnFunc(id, authUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, uint) *expense.ExpenseEntity); ok {
		r0 = returnFunc(id, authUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*expense.ExpenseEntity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint, uint) error); ok {
		r1 = returnFunc(id, authUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExpenseService_GetExpenseByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExpenseByID'
type MockExpenseService_GetExpenseByID_Call struct {
	*mock.Call
}

// GetExpenseByID is a helper method to define mock.On call
//   - id uint
//   - authUserID uint
func (_e *MockExpenseService_Expecter) GetExpenseByID(id interface{}, authUserID interface{}) *MockExpenseService_GetExpenseByID_Call {
	return &MockExpenseService_GetExpenseByID_Call{Call: _e.mock.On("GetExpenseByID", id, authUserID)}
}

func (_c *MockExpenseService_GetExpenseByID_Call) Run(run func(id uint, authUserID uint)) *MockExpenseService_GetExpenseByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockExpenseService_GetExpenseByID_Call) Return(expenseEntity *expense.ExpenseEntity, err error) *MockExpenseService_GetExpenseByID_Call {
	_c.Call.Return(expenseEntity, err)
	return _c
}

func (_c *MockExpenseService_GetExpenseByID_Call) RunAndReturn(run func(id uint, authUserID uint) (*expense.ExpenseEntity, error)) *MockExpenseService_GetExpenseByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetExpenses provides a mock function for the type MockExpenseService
func (_mock *MockExpenseService) GetExpenses(authUserID uint) ([]expense.ExpenseEntity, error) {
	ret := _mock.Called(authUserID)

	if len(ret) == 0 {
		panic("no return value specified for GetExpenses")
	}

	var r0 []expense.ExpenseEntity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) ([]expense.ExpenseEntity, error)); ok {
		return returnFunc(authUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) []expense.ExpenseEntity); ok {
		r0 = returnFunc(authUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]expense.ExpenseEntity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(authUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExpenseService_GetExpenses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExpenses'
type MockExpenseService_GetExpenses_Call struct {
	*mock.Call
}

// GetExpenses is a helper method to define mock.On call
//   - authUserID uint
func (_e *MockExpenseService_Expecter) GetExpenses(authUserID interface{}) *MockExpenseService_GetExpenses_Call {
	return &MockExpenseService_GetExpenses_Call{Call: _e.mock.On("GetExpenses", authUserID)}
}

func (_c *MockExpenseService_GetExpenses_Call) Run(run func(authUserID uint)) *MockExpenseService_GetExpenses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockExpenseService_GetExpenses_Call) Return(expenseEntitys []expense.ExpenseEntity, err error) *MockExpenseService_GetExpenses_Call {
	_c.Call.Return(expenseEntitys, err)
	return _c
}

func (_c *MockExpenseService_GetExpenses_Call) RunAndReturn(run func(authUserID uint) ([]expense.ExpenseEntity, error)) *MockExpenseService_GetExpenses_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateExpense provides a mock function for the type MockExpenseService
func (_mock *MockExpenseService) UpdateExpense(id uint, authUserID uint, dto expense.UpdateExpenseRequest) error {
	ret := _mock.Called(id, authUserID, dto)

	if len(ret) == 0 {
		panic("no return value specified for UpdateExpense")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint, uint, expense.UpdateExpenseRequest) error); ok {
		r0 = returnFunc(id, authUserID, dto)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExpenseService_UpdateExpense_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateExpense'
type MockExpenseService_UpdateExpense_Call struct {
	*mock.Call
}

// UpdateExpense is a helper method to define mock.On call
//   - id uint
//   - authUserID uint
//   - dto expense.UpdateExpenseRequest
func (_e *MockExpenseService_Expecter) UpdateExpense(id interface{}, authUserID interface{}, dto interface{}) *MockExpenseService_UpdateExpense_Call {
	return &MockExpenseService_UpdateExpense_Call{Call: _e.mock.On("UpdateExpense", id, authUserID, dto)}
}

func (_c *MockExpenseService_UpdateExpense_Call) Run(run func(id uint, authUserID uint, dto expense.UpdateExpenseRequest)) *MockExpenseService_UpdateExpense_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 expense.UpdateExpenseRequest
		if args[2] != nil {
			arg2 = args[2].(expense.UpdateExpenseRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockExpenseService_UpdateExpense_Call) Return(err error) *MockExpenseService_UpdateExpense_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExpenseService_UpdateExpense_Call) RunAndReturn(run func(id uint, authUserID uint, dto expense.UpdateExpenseRequest) error) *MockExpenseService_UpdateExpense_Call {
	_c.Call.Return(run)
	return _c
}
