// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/Perajit/expense-tracker-go/internal/expense"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTagRepository creates a new instance of MockTagRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTagRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTagRepository {
	mock := &MockTagRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTagRepository is an autogenerated mock type for the TagRepository type
type MockTagRepository struct {
	mock.Mock
}

type MockTagRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTagRepository) EXPECT() *MockTagRepository_Expecter {
	return &MockTagRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTagRepository
func (_mock *MockTagRepository) Create(tag *expense.TagEntity) error {
	ret := _mock.Called(tag)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*expense.TagEntity) error); ok {
		r0 = returnFunc(tag)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTagRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTagRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - tag *expense.TagEntity
func (_e *MockTagRepository_Expecter) Create(tag interface{}) *MockTagRepository_Create_Call {
	return &MockTagRepository_Create_Call{Call: _e.mock.On("Create", tag)}
}

func (_c *MockTagRepository_Create_Call) Run(run func(tag *expense.TagEntity)) *MockTagRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *expense.TagEntity
		if args[0] != nil {
			arg0 = args[0].(*expense.TagEntity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTagRepository_Create_Call) Return(err error) *MockTagRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTagRepository_Create_Call) RunAndReturn(run func(tag *expense.TagEntity) error) *MockTagRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockTagRepository
func (_mock *MockTagRepository) Delete(id uint) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTagRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTagRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint
func (_e *MockTagRepository_Expecter) Delete(id interface{}) *MockTagRepository_Delete_Call {
	return &MockTagRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockTagRepository_Delete_Call) Run(run func(id uint)) *MockTagRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTagRepository_Delete_Call) Return(err error) *MockTagRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTagRepository_Delete_Call) RunAndReturn(run func(id uint) error) *MockTagRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDAndUser provides a mock function for the type MockTagRepository
func (_mock *MockTagRepository) GetByIDAndUser(id uint, userID uint) (*expense.TagEntity, error) {
	ret := _mock.Called(id, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDAndUser")
	}

	var r0 *expense.TagEntity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint, uint) (*expense.TagEntity, error)); ok {
		return returnFunc(id, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, uint) *expense.TagEntity); ok {
		r0 = returnFunc(id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*expense.TagEntity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint, uint) error); ok {
		r1 = returnFunc(id, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagRepository_GetByIDAndUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDAndUser'
type MockTagRepository_GetByIDAndUser_Call struct {
	*mock.Call
}

// GetByIDAndUser is a helper method to define mock.On call
//   - id uint
//   - userID uint
func (_e *MockTagRepository_Expecter) GetByIDAndUser(id interface{}, userID interface{}) *MockTagRepository_GetByIDAndUser_Call {
	return &MockTagRepository_GetByIDAndUser_Call{Call: _e.mock.On("GetByIDAndUser", id, userID)}
}

func (_c *MockTagRepository_GetByIDAndUser_Call) Run(run func(id uint, userID uint)) *MockTagRepository_GetByIDAndUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTagRepository_GetByIDAndUser_Call) Return(tagEntity *expense.TagEntity, err error) *MockTagRepository_GetByIDAndUser_Call {
	_c.Call.Return(tagEntity, err)
	return _c
}

func (_c *MockTagRepository_GetByIDAndUser_Call) RunAndReturn(run func(id uint, userID uint) (*expense.TagEntity, error)) *MockTagRepository_GetByIDAndUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDsAndUser provides a mock function for the type MockTagRepository
func (_mock *MockTagRepository) GetByIDsAndUser(ids []uint, userID uint) ([]expense.TagEntity, error) {
	ret := _mock.Called(ids, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDsAndUser")
	}

	var r0 []expense.TagEntity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]uint, uint) ([]expense.TagEntity, error)); ok {
		return returnFunc(ids, userID)
	}
	if returnFunc, ok := ret.Get(0).(func([]uint, uint) []expense.TagEntity); ok {
		r0 = returnFunc(ids, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]expense.TagEntity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]uint, uint) error); ok {
		r1 = returnFunc(ids, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagRepository_GetByIDsAndUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDsAndUser'
type MockTagRepository_GetByIDsAndUser_Call struct {
	*mock.Call
}

// GetByIDsAndUser is a helper method to define mock.On call
//   - ids []uint
//   - userID uint
func (_e *MockTagRepository_Expecter) GetByIDsAndUser(ids interface{}, userID interface{}) *MockTagRepository_GetByIDsAndUser_Call {
	return &MockTagRepository_GetByIDsAndUser_Call{Call: _e.mock.On("GetByIDsAndUser", ids, userID)}
}

func (_c *MockTagRepository_GetByIDsAndUser_Call) Run(run func(ids []uint, userID uint)) *MockTagRepository_GetByIDsAndUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []uint
		if args[0] != nil {
			arg0 = args[0].([]uint)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTagRepository_GetByIDsAndUser_Call) Return(tagEntitys []expense.TagEntity, err error) *MockTagRepository_GetByIDsAndUser_Call {
	_c.Call.Return(tagEntitys, err)
	return _c
}

func (_c *MockTagRepository_GetByIDsAndUser_Call) RunAndReturn(run func(ids []uint, userID uint) ([]expense.TagEntity, error)) *MockTagRepository_GetByIDsAndUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUser provides a mock function for the type MockTagRepository
func (_mock *MockTagRepository) GetByUser(userID uint) ([]expense.TagEntity, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUser")
	}

	var r0 []expense.TagEntity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) ([]expense.TagEntity, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) []expense.TagEntity); ok {
		r0 = returnFunc(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]expense.TagEntity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagRepository_GetByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUser'
type MockTagRepository_GetByUser_Call struct {
	*mock.Call
}

// GetByUser is a helper method to define mock.On call
//   - userID uint
func (_e *MockTagRepository_Expecter) GetByUser(userID interface{}) *MockTagRepository_GetByUser_Call {
	return &MockTagRepository_GetByUser_Call{Call: _e.mock.On("GetByUser", userID)}
}

func (_c *MockTagRepository_GetByUser_Call) Run(run func(userID uint)) *MockTagRepository_GetByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTagRepository_GetByUser_Call) Return(tagEntitys []expense.TagEntity, err error) *MockTagRepository_GetByUser_Call {
	_c.Call.Return(tagEntitys, err)
	return _c
}

func (_c *MockTagRepository_GetByUser_Call) RunAndReturn(run func(userID uint) ([]expense.TagEntity, error)) *MockTagRepository_GetByUser_Call {
	_c.Call.Return(run)
	return _c
}

// IsOwner provides a mock function for the type MockTagRepository
func (_mock *MockTagRepository) IsOwner(id uint, userID uint) (bool, error) {
	ret := _mock.Called(id, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsOwner")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint, uint) (bool, error)); ok {
		return returnFunc(id, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, uint) bool); ok {
		r0 = returnFunc(id, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(uint, uint) error); ok {
		r1 = returnFunc(id, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagRepository_IsOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsOwner'
type MockTagRepository_IsOwner_Call struct {
	*mock.Call
}

// IsOwner is a helper method to define mock.On call
//   - id uint
//   - userID uint
func (_e *MockTagRepository_Expecter) IsOwner(id interface{}, userID interface{}) *MockTagRepository_IsOwner_Call {
	return &MockTagRepository_IsOwner_Call{Call: _e.mock.On("IsOwner", id, userID)}
}

func (_c *MockTagRepository_IsOwner_Call) Run(run func(id uint, userID uint)) *MockTagRepository_IsOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTagRepository_IsOwner_Call) Return(b bool, err error) *MockTagRepository_IsOwner_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockTagRepository_IsOwner_Call) RunAndReturn(run func(id uint, userID uint) (bool, error)) *MockTagRepository_IsOwner_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockTagRepository
func (_mock *MockTagRepository) Update(tag *expense.TagEntity) error {
	ret := _mock.Called(tag)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*expense.TagEntity) error); ok {
		r0 = returnFunc(tag)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTagRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTagRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - tag *expense.TagEntity
func (_e *MockTagRepository_Expecter) Update(tag interface{}) *MockTagRepository_Update_Call {
	return &MockTagRepository_Update_Call{Call: _e.mock.On("Update", tag)}
}

func (_c *MockTagRepository_Update_Call) Run(run func(tag *expense.TagEntity)) *MockTagRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *expense.TagEntity
		if args[0] != nil {
			arg0 = args[0].(*expense.TagEntity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTagRepository_Update_Call) Return(err error) *MockTagRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTagRepository_Update_Call) RunAndReturn(run func(tag *expense.TagEntity) error) *MockTagRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
