// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/Perajit/expense-tracker-go/internal/expense"
	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockExpenseRepository creates a new instance of MockExpenseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExpenseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExpenseRepository {
	mock := &MockExpenseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExpenseRepository is an autogenerated mock type for the ExpenseRepository type
type MockExpenseRepository struct {
	mock.Mock
}

type MockExpenseRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExpenseRepository) EXPECT() *MockExpenseRepository_Expecter {
	return &MockExpenseRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockExpenseRepository
func (_mock *MockExpenseRepository) Create(expense1 *expense.ExpenseEntity) error {
	ret := _mock.Called(expense1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*expense.ExpenseEntity) error); ok {
		r0 = returnFunc(expense1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExpenseRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockExpenseRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - expense1 *expense.ExpenseEntity
func (_e *MockExpenseRepository_Expecter) Create(expense1 interface{}) *MockExpenseRepository_Create_Call {
	return &MockExpenseRepository_Create_Call{Call: _e.mock.On("Create", expense1)}
}

func (_c *MockExpenseRepository_Create_Call) Run(run func(expense1 *expense.ExpenseEntity)) *MockExpenseRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *expense.ExpenseEntity
		if args[0] != nil {
			arg0 = args[0].(*expense.ExpenseEntity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockExpenseRepository_Create_Call) Return(err error) *MockExpenseRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExpenseRepository_Create_Call) RunAndReturn(run func(expense1 *expense.ExpenseEntity) error) *MockExpenseRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockExpenseRepository
func (_mock *MockExpenseRepository) Delete(id uint) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExpenseRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockExpenseRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint
func (_e *MockExpenseRepository_Expecter) Delete(id interface{}) *MockExpenseRepository_Delete_Call {
	return &MockExpenseRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockExpenseRepository_Delete_Call) Run(run func(id uint)) *MockExpenseRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockExpenseRepository_Delete_Call) Return(err error) *MockExpenseRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExpenseRepository_Delete_Call) RunAndReturn(run func(id uint) error) *MockExpenseRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDAndUser provides a mock function for the type MockExpenseRepository
func (_mock *MockExpenseRepository) GetByIDAndUser(id uint, userID uint) (*expense.ExpenseEntity, error) {
	ret := _mock.Called(id, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDAndUser")
	}

	var r0 *expense.ExpenseEntity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint, uint) (*expense.ExpenseEntity, error)); ok {
		return returnFunc(id, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, uint) *expense.ExpenseEntity); ok {
		r0 = returnFunc(id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*expense.ExpenseEntity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint, uint) error); ok {
		r1 = returnFunc(id, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExpenseRepository_GetByIDAndUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDAndUser'
type MockExpenseRepository_GetByIDAndUser_Call struct {
	*mock.Call
}

// GetByIDAndUser is a helper method to define mock.On call
//   - id uint
//   - userID uint
func (_e *MockExpenseRepository_Expecter) GetByIDAndUser(id interface{}, userID interface{}) *MockExpenseRepository_GetByIDAndUser_Call {
	return &MockExpenseRepository_GetByIDAndUser_Call{Call: _e.mock.On("GetByIDAndUser", id, userID)}
}

func (_c *MockExpenseRepository_GetByIDAndUser_Call) Run(run func(id uint, userID uint)) *MockExpenseRepository_GetByIDAndUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockExpenseRepository_GetByIDAndUser_Call) Return(expenseEntity *expense.ExpenseEntity, err error) *MockExpenseRepository_GetByIDAndUser_Call {
	_c.Call.Return(expenseEntity, err)
	return _c
}

func (_c *MockExpenseRepository_GetByIDAndUser_Call) RunAndReturn(run func(id uint, userID uint) (*expense.ExpenseEntity, error)) *MockExpenseRepository_GetByIDAndUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDAndUserNoAssociation provides a mock function for the type MockExpenseRepository
func (_mock *MockExpenseRepository) GetByIDAndUserNoAssociation(id uint, userID uint) (*expense.ExpenseEntity, error) {
	ret := _mock.Called(id, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDAndUserNoAssociation")
	}

	var r0 *expense.ExpenseEntity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint, uint) (*expense.ExpenseEntity, error)); ok {
		return returnFunc(id, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, uint) *expense.ExpenseEntity); ok {
		r0 = returnFunc(id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*expense.ExpenseEntity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint, uint) error); ok {
		r1 = returnFunc(id, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExpenseRepository_GetByIDAndUserNoAssociation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDAndUserNoAssociation'
type MockExpenseRepository_GetByIDAndUserNoAssociation_Call struct {
	*mock.Call
}

// GetByIDAndUserNoAssociation is a helper method to define mock.On call
//   - id uint
//   - userID uint
func (_e *MockExpenseRepository_Expecter) GetByIDAndUserNoAssociation(id interface{}, userID interface{}) *MockExpenseRepository_GetByIDAndUserNoAssociation_Call {
	return &MockExpenseRepository_GetByIDAndUserNoAssociation_Call{Call: _e.mock.On("GetByIDAndUserNoAssociation", id, userID)}
}

func (_c *MockExpenseRepository_GetByIDAndUserNoAssociation_Call) Run(run func(id uint, userID uint)) *MockExpenseRepository_GetByIDAndUserNoAssociation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockExpenseRepository_GetByIDAndUserNoAssociation_Call) Return(expenseEntity *expense.ExpenseEntity, err error) *MockExpenseRepository_GetByIDAndUserNoAssociation_Call {
	_c.Call.Return(expenseEntity, err)
	return _c
}

func (_c *MockExpenseRepository_GetByIDAndUserNoAssociation_Call) RunAndReturn(run func(id uint, userID uint) (*expense.ExpenseEntity, error)) *MockExpenseRepository_GetByIDAndUserNoAssociation_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUser provides a mock function for the type MockExpenseRepository
func (_mock *MockExpenseRepository) GetByUser(userID uint) ([]expense.ExpenseEntity, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUser")
	}

	var r0 []expense.ExpenseEntity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) ([]expense.ExpenseEntity, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) []expense.ExpenseEntity); ok {
		r0 = returnFunc(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]expense.ExpenseEntity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExpenseRepository_GetByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUser'
type MockExpenseRepository_GetByUser_Call struct {
	*mock.Call
}

// GetByUser is a helper method to define mock.On call
//   - userID uint
func (_e *MockExpenseRepository_Expecter) GetByUser(userID interface{}) *MockExpenseRepository_GetByUser_Call {
	return &MockExpenseRepository_GetByUser_Call{Call: _e.mock.On("GetByUser", userID)}
}

func (_c *MockExpenseRepository_GetByUser_Call) Run(run func(userID uint)) *MockExpenseRepository_GetByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockExpenseRepository_GetByUser_Call) Return(expenseEntitys []expense.ExpenseEntity, err error) *MockExpenseRepository_GetByUser_Call {
	_c.Call.Return(expenseEntitys, err)
	return _c
}

func (_c *MockExpenseRepository_GetByUser_Call) RunAndReturn(run func(userID uint) ([]expense.ExpenseEntity, error)) *MockExpenseRepository_GetByUser_Call {
	_c.Call.Return(run)
	return _c
}

// IsOwner provides a mock function for the type MockExpenseRepository
func (_mock *MockExpenseRepository) IsOwner(id uint, userID uint) (bool, error) {
	ret := _mock.Called(id, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsOwner")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint, uint) (bool, error)); ok {
		return returnFunc(id, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, uint) bool); ok {
		r0 = returnFunc(id, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(uint, uint) error); ok {
		r1 = returnFunc(id, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExpenseRepository_IsOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsOwner'
type MockExpenseRepository_IsOwner_Call struct {
	*mock.Call
}

// IsOwner is a helper method to define mock.On call
//   - id uint
//   - userID uint
func (_e *MockExpenseRepository_Expecter) IsOwner(id interface{}, userID interface{}) *MockExpenseRepository_IsOwner_Call {
	return &MockExpenseRepository_IsOwner_Call{Call: _e.mock.On("IsOwner", id, userID)}
}

func (_c *MockExpenseRepository_IsOwner_Call) Run(run func(id uint, userID uint)) *MockExpenseRepository_IsOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockExpenseRepository_IsOwner_Call) Return(b bool, err error) *MockExpenseRepository_IsOwner_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockExpenseRepository_IsOwner_Call) RunAndReturn(run func(id uint, userID uint) (bool, error)) *MockExpenseRepository_IsOwner_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockExpenseRepository
func (_mock *MockExpenseRepository) Update(expense1 *expense.ExpenseEntity) error {
	ret := _mock.Called(expense1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*expense.ExpenseEntity) error); ok {
		r0 = returnFunc(expense1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExpenseRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockExpenseRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - expense1 *expense.ExpenseEntity
func (_e *MockExpenseRepository_Expecter) Update(expense1 interface{}) *MockExpenseRepository_Update_Call {
	return &MockExpenseRepository_Update_Call{Call: _e.mock.On("Update", expense1)}
}

func (_c *MockExpenseRepository_Update_Call) Run(run func(expense1 *expense.ExpenseEntity)) *MockExpenseRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *expense.ExpenseEntity
		if args[0] != nil {
			arg0 = args[0].(*expense.ExpenseEntity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockExpenseRepository_Update_Call) Return(err error) *MockExpenseRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExpenseRepository_Update_Call) RunAndReturn(run func(expense1 *expense.ExpenseEntity) error) *MockExpenseRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTags provides a mock function for the type MockExpenseRepository
func (_mock *MockExpenseRepository) UpdateTags(expense1 *expense.ExpenseEntity, tags []expense.TagEntity) error {
	ret := _mock.Called(expense1, tags)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTags")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*expense.ExpenseEntity, []expense.TagEntity) error); ok {
		r0 = returnFunc(expense1, tags)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExpenseRepository_UpdateTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTags'
type MockExpenseRepository_UpdateTags_Call struct {
	*mock.Call
}

// UpdateTags is a helper method to define mock.On call
//   - expense1 *expense.ExpenseEntity
//   - tags []expense.TagEntity
func (_e *MockExpenseRepository_Expecter) UpdateTags(expense1 interface{}, tags interface{}) *MockExpenseRepository_UpdateTags_Call {
	return &MockExpenseRepository_UpdateTags_Call{Call: _e.mock.On("UpdateTags", expense1, tags)}
}

func (_c *MockExpenseRepository_UpdateTags_Call) Run(run func(expense1 *expense.ExpenseEntity, tags []expense.TagEntity)) *MockExpenseRepository_UpdateTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *expense.ExpenseEntity
		if args[0] != nil {
			arg0 = args[0].(*expense.ExpenseEntity)
		}
		var arg1 []expense.TagEntity
		if args[1] != nil {
			arg1 = args[1].([]expense.TagEntity)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockExpenseRepository_UpdateTags_Call) Return(err error) *MockExpenseRepository_UpdateTags_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExpenseRepository_UpdateTags_Call) RunAndReturn(run func(expense1 *expense.ExpenseEntity, tags []expense.TagEntity) error) *MockExpenseRepository_UpdateTags_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function for the type MockExpenseRepository
func (_mock *MockExpenseRepository) WithTx(tx *gorm.DB) expense.ExpenseRepository {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 expense.ExpenseRepository
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) expense.ExpenseRepository); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(expense.ExpenseRepository)
		}
	}
	return r0
}

// MockExpenseRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockExpenseRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *MockExpenseRepository_Expecter) WithTx(tx interface{}) *MockExpenseRepository_WithTx_Call {
	return &MockExpenseRepository_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *MockExpenseRepository_WithTx_Call) Run(run func(tx *gorm.DB)) *MockExpenseRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockExpenseRepository_WithTx_Call) Return(expenseRepository expense.ExpenseRepository) *MockExpenseRepository_WithTx_Call {
	_c.Call.Return(expenseRepository)
	return _c
}

func (_c *MockExpenseRepository_WithTx_Call) RunAndReturn(run func(tx *gorm.DB) expense.ExpenseRepository) *MockExpenseRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}
