// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/Perajit/expense-tracker-go/internal/expense"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCategoryService creates a new instance of MockCategoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCategoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCategoryService {
	mock := &MockCategoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCategoryService is an autogenerated mock type for the CategoryService type
type MockCategoryService struct {
	mock.Mock
}

type MockCategoryService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCategoryService) EXPECT() *MockCategoryService_Expecter {
	return &MockCategoryService_Expecter{mock: &_m.Mock}
}

// CreateCategory provides a mock function for the type MockCategoryService
func (_mock *MockCategoryService) CreateCategory(authUserID uint, dto expense.CreateCategoryRequest) (*expense.CategoryEntity, error) {
	ret := _mock.Called(authUserID, dto)

	if len(ret) == 0 {
		panic("no return value specified for CreateCategory")
	}

	var r0 *expense.CategoryEntity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint, expense.CreateCategoryRequest) (*expense.CategoryEntity, error)); ok {
		return returnFunc(authUserID, dto)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, expense.CreateCategoryRequest) *expense.CategoryEntity); ok {
		r0 = returnFunc(authUserID, dto)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*expense.CategoryEntity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint, expense.CreateCategoryRequest) error); ok {
		r1 = returnFunc(authUserID, dto)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategoryService_CreateCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCategory'
type MockCategoryService_CreateCategory_Call struct {
	*mock.Call
}

// CreateCategory is a helper method to define mock.On call
//   - authUserID uint
//   - dto expense.CreateCategoryRequest
func (_e *MockCategoryService_Expecter) CreateCategory(authUserID interface{}, dto interface{}) *MockCategoryService_CreateCategory_Call {
	return &MockCategoryService_CreateCategory_Call{Call: _e.mock.On("CreateCategory", authUserID, dto)}
}

func (_c *MockCategoryService_CreateCategory_Call) Run(run func(authUserID uint, dto expense.CreateCategoryRequest)) *MockCategoryService_CreateCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 expense.CreateCategoryRequest
		if args[1] != nil {
			arg1 = args[1].(expense.CreateCategoryRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCategoryService_CreateCategory_Call) Return(categoryEntity *expense.CategoryEntity, err error) *MockCategoryService_CreateCategory_Call {
	_c.Call.Return(categoryEntity, err)
	return _c
}

func (_c *MockCategoryService_CreateCategory_Call) RunAndReturn(run func(authUserID uint, dto expense.CreateCategoryRequest) (*expense.CategoryEntity, error)) *MockCategoryService_CreateCategory_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCategory provides a mock function for the type MockCategoryService
func (_mock *MockCategoryService) DeleteCategory(id uint, userId uint) error {
	ret := _mock.Called(id, userId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCategory")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint, uint) error); ok {
		r0 = returnFunc(id, userId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCategoryService_DeleteCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCategory'
type MockCategoryService_DeleteCategory_Call struct {
	*mock.Call
}

// DeleteCategory is a helper method to define mock.On call
//   - id uint
//   - userId uint
func (_e *MockCategoryService_Expecter) DeleteCategory(id interface{}, userId interface{}) *MockCategoryService_DeleteCategory_Call {
	return &MockCategoryService_DeleteCategory_Call{Call: _e.mock.On("DeleteCategory", id, userId)}
}

func (_c *MockCategoryService_DeleteCategory_Call) Run(run func(id uint, userId uint)) *MockCategoryService_DeleteCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCategoryService_DeleteCategory_Call) Return(err error) *MockCategoryService_DeleteCategory_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCategoryService_DeleteCategory_Call) RunAndReturn(run func(id uint, userId uint) error) *MockCategoryService_DeleteCategory_Call {
	_c.Call.Return(run)
	return _c
}

// GetCategories provides a mock function for the type MockCategoryService
func (_mock *MockCategoryService) GetCategories(authUserID uint) ([]expense.CategoryEntity, error) {
	ret := _mock.Called(authUserID)

	if len(ret) == 0 {
		panic("no return value specified for GetCategories")
	}

	var r0 []expense.CategoryEntity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) ([]expense.CategoryEntity, error)); ok {
		return returnFunc(authUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) []expense.CategoryEntity); ok {
		r0 = returnFunc(authUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]expense.CategoryEntity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(authUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategoryService_GetCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCategories'
type MockCategoryService_GetCategories_Call struct {
	*mock.Call
}

// GetCategories is a helper method to define mock.On call
//   - authUserID uint
func (_e *MockCategoryService_Expecter) GetCategories(authUserID interface{}) *MockCategoryService_GetCategories_Call {
	return &MockCategoryService_GetCategories_Call{Call: _e.mock.On("GetCategories", authUserID)}
}

func (_c *MockCategoryService_GetCategories_Call) Run(run func(authUserID uint)) *MockCategoryService_GetCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCategoryService_GetCategories_Call) Return(categoryEntitys []expense.CategoryEntity, err error) *MockCategoryService_GetCategories_Call {
	_c.Call.Return(categoryEntitys, err)
	return _c
}

func (_c *MockCategoryService_GetCategories_Call) RunAndReturn(run func(authUserID uint) ([]expense.CategoryEntity, error)) *MockCategoryService_GetCategories_Call {
	_c.Call.Return(run)
	return _c
}

// GetCategoryByID provides a mock function for the type MockCategoryService
func (_mock *MockCategoryService) GetCategoryByID(id uint, authUserID *uint) (*expense.CategoryEntity, error) {
	ret := _mock.Called(id, authUserID)

	if len(ret) == 0 {
		panic("no return value specified for GetCategoryByID")
	}

	var r0 *expense.CategoryEntity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint, *uint) (*expense.CategoryEntity, error)); ok {
		return returnFunc(id, authUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, *uint) *expense.CategoryEntity); ok {
		r0 = returnFunc(id, authUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*expense.CategoryEntity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint, *uint) error); ok {
		r1 = returnFunc(id, authUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategoryService_GetCategoryByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCategoryByID'
type MockCategoryService_GetCategoryByID_Call struct {
	*mock.Call
}

// GetCategoryByID is a helper method to define mock.On call
//   - id uint
//   - authUserID *uint
func (_e *MockCategoryService_Expecter) GetCategoryByID(id interface{}, authUserID interface{}) *MockCategoryService_GetCategoryByID_Call {
	return &MockCategoryService_GetCategoryByID_Call{Call: _e.mock.On("GetCategoryByID", id, authUserID)}
}

func (_c *MockCategoryService_GetCategoryByID_Call) Run(run func(id uint, authUserID *uint)) *MockCategoryService_GetCategoryByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 *uint
		if args[1] != nil {
			arg1 = args[1].(*uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCategoryService_GetCategoryByID_Call) Return(categoryEntity *expense.CategoryEntity, err error) *MockCategoryService_GetCategoryByID_Call {
	_c.Call.Return(categoryEntity, err)
	return _c
}

func (_c *MockCategoryService_GetCategoryByID_Call) RunAndReturn(run func(id uint, authUserID *uint) (*expense.CategoryEntity, error)) *MockCategoryService_GetCategoryByID_Call {
	_c.Call.Return(run)
	return _c
}

// IsCategoryOwner provides a mock function for the type MockCategoryService
func (_mock *MockCategoryService) IsCategoryOwner(id uint, authUserID uint) (bool, error) {
	ret := _mock.Called(id, authUserID)

	if len(ret) == 0 {
		panic("no return value specified for IsCategoryOwner")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint, uint) (bool, error)); ok {
		return returnFunc(id, authUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, uint) bool); ok {
		r0 = returnFunc(id, authUserID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(uint, uint) error); ok {
		r1 = returnFunc(id, authUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategoryService_IsCategoryOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsCategoryOwner'
type MockCategoryService_IsCategoryOwner_Call struct {
	*mock.Call
}

// IsCategoryOwner is a helper method to define mock.On call
//   - id uint
//   - authUserID uint
func (_e *MockCategoryService_Expecter) IsCategoryOwner(id interface{}, authUserID interface{}) *MockCategoryService_IsCategoryOwner_Call {
	return &MockCategoryService_IsCategoryOwner_Call{Call: _e.mock.On("IsCategoryOwner", id, authUserID)}
}

func (_c *MockCategoryService_IsCategoryOwner_Call) Run(run func(id uint, authUserID uint)) *MockCategoryService_IsCategoryOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCategoryService_IsCategoryOwner_Call) Return(b bool, err error) *MockCategoryService_IsCategoryOwner_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockCategoryService_IsCategoryOwner_Call) RunAndReturn(run func(id uint, authUserID uint) (bool, error)) *MockCategoryService_IsCategoryOwner_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCategory provides a mock function for the type MockCategoryService
func (_mock *MockCategoryService) UpdateCategory(id uint, authUserID uint, dto expense.UpdateCategoryRequest) error {
	ret := _mock.Called(id, authUserID, dto)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCategory")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint, uint, expense.UpdateCategoryRequest) error); ok {
		r0 = returnFunc(id, authUserID, dto)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCategoryService_UpdateCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCategory'
type MockCategoryService_UpdateCategory_Call struct {
	*mock.Call
}

// UpdateCategory is a helper method to define mock.On call
//   - id uint
//   - authUserID uint
//   - dto expense.UpdateCategoryRequest
func (_e *MockCategoryService_Expecter) UpdateCategory(id interface{}, authUserID interface{}, dto interface{}) *MockCategoryService_UpdateCategory_Call {
	return &MockCategoryService_UpdateCategory_Call{Call: _e.mock.On("UpdateCategory", id, authUserID, dto)}
}

func (_c *MockCategoryService_UpdateCategory_Call) Run(run func(id uint, authUserID uint, dto expense.UpdateCategoryRequest)) *MockCategoryService_UpdateCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 expense.UpdateCategoryRequest
		if args[2] != nil {
			arg2 = args[2].(expense.UpdateCategoryRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCategoryService_UpdateCategory_Call) Return(err error) *MockCategoryService_UpdateCategory_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCategoryService_UpdateCategory_Call) RunAndReturn(run func(id uint, authUserID uint, dto expense.UpdateCategoryRequest) error) *MockCategoryService_UpdateCategory_Call {
	_c.Call.Return(run)
	return _c
}
