// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/Perajit/expense-tracker-go/internal/expense"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCategoryRepository creates a new instance of MockCategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCategoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCategoryRepository {
	mock := &MockCategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCategoryRepository is an autogenerated mock type for the CategoryRepository type
type MockCategoryRepository struct {
	mock.Mock
}

type MockCategoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCategoryRepository) EXPECT() *MockCategoryRepository_Expecter {
	return &MockCategoryRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockCategoryRepository
func (_mock *MockCategoryRepository) Create(category *expense.CategoryEntity) error {
	ret := _mock.Called(category)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*expense.CategoryEntity) error); ok {
		r0 = returnFunc(category)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCategoryRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCategoryRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - category *expense.CategoryEntity
func (_e *MockCategoryRepository_Expecter) Create(category interface{}) *MockCategoryRepository_Create_Call {
	return &MockCategoryRepository_Create_Call{Call: _e.mock.On("Create", category)}
}

func (_c *MockCategoryRepository_Create_Call) Run(run func(category *expense.CategoryEntity)) *MockCategoryRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *expense.CategoryEntity
		if args[0] != nil {
			arg0 = args[0].(*expense.CategoryEntity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCategoryRepository_Create_Call) Return(err error) *MockCategoryRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCategoryRepository_Create_Call) RunAndReturn(run func(category *expense.CategoryEntity) error) *MockCategoryRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockCategoryRepository
func (_mock *MockCategoryRepository) Delete(id uint) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCategoryRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCategoryRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint
func (_e *MockCategoryRepository_Expecter) Delete(id interface{}) *MockCategoryRepository_Delete_Call {
	return &MockCategoryRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockCategoryRepository_Delete_Call) Run(run func(id uint)) *MockCategoryRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCategoryRepository_Delete_Call) Return(err error) *MockCategoryRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCategoryRepository_Delete_Call) RunAndReturn(run func(id uint) error) *MockCategoryRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByName provides a mock function for the type MockCategoryRepository
func (_mock *MockCategoryRepository) ExistsByName(userID uint, name string) (bool, error) {
	ret := _mock.Called(userID, name)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByName")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint, string) (bool, error)); ok {
		return returnFunc(userID, name)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, string) bool); ok {
		r0 = returnFunc(userID, name)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(uint, string) error); ok {
		r1 = returnFunc(userID, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategoryRepository_ExistsByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByName'
type MockCategoryRepository_ExistsByName_Call struct {
	*mock.Call
}

// ExistsByName is a helper method to define mock.On call
//   - userID uint
//   - name string
func (_e *MockCategoryRepository_Expecter) ExistsByName(userID interface{}, name interface{}) *MockCategoryRepository_ExistsByName_Call {
	return &MockCategoryRepository_ExistsByName_Call{Call: _e.mock.On("ExistsByName", userID, name)}
}

func (_c *MockCategoryRepository_ExistsByName_Call) Run(run func(userID uint, name string)) *MockCategoryRepository_ExistsByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCategoryRepository_ExistsByName_Call) Return(b bool, err error) *MockCategoryRepository_ExistsByName_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockCategoryRepository_ExistsByName_Call) RunAndReturn(run func(userID uint, name string) (bool, error)) *MockCategoryRepository_ExistsByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDAndUser provides a mock function for the type MockCategoryRepository
func (_mock *MockCategoryRepository) GetByIDAndUser(id uint, userID *uint) (*expense.CategoryEntity, error) {
	ret := _mock.Called(id, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDAndUser")
	}

	var r0 *expense.CategoryEntity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint, *uint) (*expense.CategoryEntity, error)); ok {
		return returnFunc(id, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, *uint) *expense.CategoryEntity); ok {
		r0 = returnFunc(id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*expense.CategoryEntity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint, *uint) error); ok {
		r1 = returnFunc(id, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategoryRepository_GetByIDAndUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDAndUser'
type MockCategoryRepository_GetByIDAndUser_Call struct {
	*mock.Call
}

// GetByIDAndUser is a helper method to define mock.On call
//   - id uint
//   - userID *uint
func (_e *MockCategoryRepository_Expecter) GetByIDAndUser(id interface{}, userID interface{}) *MockCategoryRepository_GetByIDAndUser_Call {
	return &MockCategoryRepository_GetByIDAndUser_Call{Call: _e.mock.On("GetByIDAndUser", id, userID)}
}

func (_c *MockCategoryRepository_GetByIDAndUser_Call) Run(run func(id uint, userID *uint)) *MockCategoryRepository_GetByIDAndUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 *uint
		if args[1] != nil {
			arg1 = args[1].(*uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCategoryRepository_GetByIDAndUser_Call) Return(categoryEntity *expense.CategoryEntity, err error) *MockCategoryRepository_GetByIDAndUser_Call {
	_c.Call.Return(categoryEntity, err)
	return _c
}

func (_c *MockCategoryRepository_GetByIDAndUser_Call) RunAndReturn(run func(id uint, userID *uint) (*expense.CategoryEntity, error)) *MockCategoryRepository_GetByIDAndUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUser provides a mock function for the type MockCategoryRepository
func (_mock *MockCategoryRepository) GetByUser(userID uint) ([]expense.CategoryEntity, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUser")
	}

	var r0 []expense.CategoryEntity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) ([]expense.CategoryEntity, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) []expense.CategoryEntity); ok {
		r0 = returnFunc(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]expense.CategoryEntity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategoryRepository_GetByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUser'
type MockCategoryRepository_GetByUser_Call struct {
	*mock.Call
}

// GetByUser is a helper method to define mock.On call
//   - userID uint
func (_e *MockCategoryRepository_Expecter) GetByUser(userID interface{}) *MockCategoryRepository_GetByUser_Call {
	return &MockCategoryRepository_GetByUser_Call{Call: _e.mock.On("GetByUser", userID)}
}

func (_c *MockCategoryRepository_GetByUser_Call) Run(run func(userID uint)) *MockCategoryRepository_GetByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCategoryRepository_GetByUser_Call) Return(categoryEntitys []expense.CategoryEntity, err error) *MockCategoryRepository_GetByUser_Call {
	_c.Call.Return(categoryEntitys, err)
	return _c
}

func (_c *MockCategoryRepository_GetByUser_Call) RunAndReturn(run func(userID uint) ([]expense.CategoryEntity, error)) *MockCategoryRepository_GetByUser_Call {
	_c.Call.Return(run)
	return _c
}

// IsOwner provides a mock function for the type MockCategoryRepository
func (_mock *MockCategoryRepository) IsOwner(id uint, userID uint) (bool, error) {
	ret := _mock.Called(id, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsOwner")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint, uint) (bool, error)); ok {
		return returnFunc(id, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, uint) bool); ok {
		r0 = returnFunc(id, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(uint, uint) error); ok {
		r1 = returnFunc(id, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategoryRepository_IsOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsOwner'
type MockCategoryRepository_IsOwner_Call struct {
	*mock.Call
}

// IsOwner is a helper method to define mock.On call
//   - id uint
//   - userID uint
func (_e *MockCategoryRepository_Expecter) IsOwner(id interface{}, userID interface{}) *MockCategoryRepository_IsOwner_Call {
	return &MockCategoryRepository_IsOwner_Call{Call: _e.mock.On("IsOwner", id, userID)}
}

func (_c *MockCategoryRepository_IsOwner_Call) Run(run func(id uint, userID uint)) *MockCategoryRepository_IsOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCategoryRepository_IsOwner_Call) Return(b bool, err error) *MockCategoryRepository_IsOwner_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockCategoryRepository_IsOwner_Call) RunAndReturn(run func(id uint, userID uint) (bool, error)) *MockCategoryRepository_IsOwner_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockCategoryRepository
func (_mock *MockCategoryRepository) Update(category *expense.CategoryEntity) error {
	ret := _mock.Called(category)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*expense.CategoryEntity) error); ok {
		r0 = returnFunc(category)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCategoryRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCategoryRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - category *expense.CategoryEntity
func (_e *MockCategoryRepository_Expecter) Update(category interface{}) *MockCategoryRepository_Update_Call {
	return &MockCategoryRepository_Update_Call{Call: _e.mock.On("Update", category)}
}

func (_c *MockCategoryRepository_Update_Call) Run(run func(category *expense.CategoryEntity)) *MockCategoryRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *expense.CategoryEntity
		if args[0] != nil {
			arg0 = args[0].(*expense.CategoryEntity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCategoryRepository_Update_Call) Return(err error) *MockCategoryRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCategoryRepository_Update_Call) RunAndReturn(run func(category *expense.CategoryEntity) error) *MockCategoryRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
